---
title: 10.2.3 Java 7提供的多异常捕获机制
categories: 
  - 1 疯狂Java讲义 (第4版)
  - 第10章 异常处理
  - 10.2 异常处理机制
abbrlink: af74f2a8
date: 2019-07-12 23:50:43
updated: 2022-04-03 01:21:14
---
# 10.2.3 Java 7提供的多异常捕获机制 #
**在`Java 7`以前,每个`catch`块只能捕获一种类型的异常**;但**从`Java 7`开始,一个`catch`块可以捕获多种类型的异常**。
使用一个`catch`块捕获多种类型的异常时需要注意如下两个地方。
- 捕获多种类型的异常时,**多种异常类型之间用竖线(`|`)隔开**。
- **捕获多种类型的异常时,异常变量有隐式的`final`修饰**,因此**程序不能对异常变量重新赋值**

## 示例程序 ##
下面程序示范了`Java 7`提供的多异常捕获。
```java
public class MultiExceptionTest
{
    public static void main(String[] args)
    {
        try
        {
            int a = Integer.parseInt(args[0]);
            int b = Integer.parseInt(args[1]);
            int c = a / b;
            System.out.println("您输入的两个数相除的结果是：" + c );
        }
        catch (IndexOutOfBoundsException|NumberFormatException
            |ArithmeticException ie)
        {
            System.out.println("程序发生了数组越界、数字格式异常、算术异常之一");
            // 捕捉多异常时，异常变量默认有final修饰，
            // 所以下面代码有错：
            ie = new ArithmeticException("test");  // ①
        }
        catch (Exception e)
        {
            System.out.println("未知异常");
            // 只捕捉一个类型的异常时，异常变量没有final修饰
            // 所以下面代码完全正确。
            e = new RuntimeException("test");    // ②
        }
    }
}
```
上面程序中使用了`IndexOutOfBoundsException|NumberFormatException|ArithmeticException`来定义异常类型,这就表明该`catch`块可以同时捕获这三种类型的异常。
## 单异常捕获可以对异常变量重新赋值
- **捕获多种类型的异常时,异常变量使用隐式的`final`修饰**,`final`修饰的变量初始化后就无法更改,因此上面程序中①号代码将产生编译错误;
- 捕获一种类型的异常时,异常变量没有`final`修饰,因此上面程序中②号代码完全正确。

## 总结 ##
`Java 7`后`catch`块可以捕获多个异常,捕获多异常时,每个异常以竖杠分隔,多个异常变量隐式使用`final`修饰,**不可以在捕获多异常的`catch`块中给异常变量重新赋值**。

